# Server settings
serverHost: localhost
serverPort: 8080

# Database settings
# Allowed Database Types: 'REDIS'
databaseType: REDIS
shouldUseEmbeddedDb: true
databaseConfigs:
  REDIS:
    name: hawkdb
    host: localhost
    port: 6379
    username:
    password:

# Provider settings
oAuthProviderConfigs:
  GITHUB:
    accessTokenUrl:
    clientId:
    clientSecret:
    isEnabled: false

## Folder settings
materialsDestination: Materials
artifactsDestination: Artifacts

# Worker settings
# Min 1 second; Max 30 seconds
pipelineSchedulerPollInterval: 4
materialTrackerPollInterval: 4

